---
env:
  contexts:
    - name: notes-kubernetes
      urls:
        - "http://frontend-service.devops-portfolio.svc.cluster.local"
      includePaths:
        - "http://frontend-service\\.devops-portfolio\\.svc\\.cluster\\.local/.*"

  parameters:
    failOnError: true
    failOnWarning: false
    progressToStdout: true

jobs:
  - type: spider
    parameters:
      context: notes-kubernetes
      url: "http://frontend-service.devops-portfolio.svc.cluster.local"
      maxDuration: 2

  - type: spiderAjax
    parameters:
      context: notes-kubernetes
      url: "http://frontend-service.devops-portfolio.svc.cluster.local"
      maxDuration: 2
      browserId: firefox-headless

  - type: passiveScan-wait
    parameters:
      maxDuration: 5

  - type: activeScan
    parameters:
      context: notes-kubernetes
      policy: "Default Policy"
      maxScanDurationInMins: 5

  - type: report
    parameters:
      template: traditional-html
      reportDir: /zap/wrk/reports
      reportFile: zap-k8s-report.html
      reportTitle: "Notes App Kubernetes - Security Scan"

  - type: report
    parameters:
      template: traditional-json
      reportDir: /zap/wrk/reports
      reportFile: zap-k8s-report.json
      reportTitle: "Notes App Kubernetes - Security Scan"
